server {
    listen 80 default_server;
    server_name _;

    location /proxy-health {
        default_type text/plain;
        return 200 "DEFAULT OK\n";
    }

    location /route-info {
        default_type text/plain;
        return 200 "dominio=no_configurado\nbackend=none\n";
    }
}

server {
    listen 80;
    server_name www.clientea.com clientea.com;

    location /proxy-health {
        default_type text/plain;
        return 200 "Cliente A OK\n";
    }

    location /route-info {
        default_type text/plain;
        return 200 "cliente=clientea\nbackend=lb-cliente-a\n";
    }

    location / {
        proxy_pass http://lb-cliente-a:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Tenant clientea;
    }
}

server {
    listen 80;
    server_name www.clienteb.com clienteb.com;

    location /proxy-health {
        default_type text/plain;
        return 200 "Cliente B OK\n";
    }

    location /route-info {
        default_type text/plain;
        return 200 "cliente=clienteb\nbackend=lb-cliente-b\n";
    }

    location / {
        proxy_pass http://lb-cliente-b:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Tenant clienteb;
    }
}