server {
    listen 80 default_server;
    server_name _;

    location /proxy-health {
        return 200 "DEFAULT OK\n";
    }
}

server {
    listen 80;
    server_name www.clientea.com;

    location /proxy-health {
        return 200 "Cliente A OK\n";
    }

    location /route-info {
        return 200 "cliente=clientea\nbackend=lb-cliente-a\n";
    }
}

server {
    listen 80;
    server_name www.clienteb.com;

    location /proxy-health {
        return 200 "Cliente B OK\n";
    }

    location /route-info {
        return 200 "cliente=clienteb\nbackend=lb-cliente-b\n";
    }
}
